import { env } from "@/lib/runtime-env";
import { requireRequestUser } from "./current-user";
import {socialHref} from "./social-contacts";
import { INTRODUCTION_VERSION } from "./introduction";
export function campusJson(data:unknown,init:ResponseInit={}){const headers=new Headers(init.headers);headers.set("Cache-Control","no-store");return Response.json(data,{...init,headers});}
export function collegeEmail(value:unknown){const email=typeof value==="string"?value.trim().toLowerCase():"";return /^[a-z0-9.!#$%&'*+/=?^_`{|}~-]+@woxsen\.edu\.in$/.test(email)&&email.length<=254?email:null;}
export function verificationFor(userId:string){return env.DB.prepare("SELECT verified_email AS collegeEmail,verified_at AS verifiedAt FROM college_verifications WHERE user_id=? AND verified_email IS NOT NULL").bind(userId).first<{collegeEmail:string;verifiedAt:number}>();}
export async function requireCampusUser(request:Request,requireSocial=true,requireCompleted=true){const user=requireRequestUser(request);if(user instanceof Response)return user;try{if(await env.DB.prepare("SELECT user_id FROM campus_suspensions WHERE user_id=?").bind(user.userId).first())return campusJson({error:"Your campus access is paused. Contact the pilot administrator."},{status:403});const v=await verificationFor(user.userId);if(!v)return campusJson({error:"Verify your @woxsen.edu.in email in My profile first.",needsVerification:true},{status:403});const p=await env.DB.prepare("SELECT social_contacts AS contacts, profile_completed AS profileCompleted, onboarding_version AS onboardingVersion FROM profiles WHERE user_id=?").bind(user.userId).first<{contacts:string;profileCompleted:number;onboardingVersion:number}>();if(requireCompleted&&(!p?.profileCompleted||p.onboardingVersion!==INTRODUCTION_VERSION))return campusJson({error:"Finish the WoxRadar questions before opening campus features.",needsProfile:true},{status:409});if(requireSocial){let valid=false;try{const c=JSON.parse(p?.contacts??"[]");valid=Array.isArray(c)&&c.some(x=>x&&typeof x.value==="string"&&socialHref(x));}catch{/* Incomplete profiles do not pass. */}if(!valid)return campusJson({error:"Add and save at least one social handle or profile link in My profile first.",needsProfile:true},{status:409});}return {...user,collegeEmail:v.collegeEmail};}catch{return campusJson({error:"College access could not be checked. Retry."},{status:503});}}
export function isModerator(id:string,email?:string){return(env.MODERATOR_USER_IDS??"").split(",").map(v=>v.trim()).filter(Boolean).includes(id)||Boolean(email&&(env.MODERATOR_EMAILS??"").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean).includes(email.toLowerCase()));}
