"use client";
import {useEffect,useState,type FormEvent} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import Moderation from "../moderation/page";
type Dashboard={role:string;summary:Record<string,number>;users:{id:string;name:string;email:string;school:string;year:string;admin:number}[];logs:{actor:string;action:string;target:string;createdAt:number}[];email:null|{configured:boolean;provider:string;sender:string;storageReady:boolean};error?:string;message?:string;ok?:boolean};
export default function Admin(){
 const [data,setData]=useState<Dashboard|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[provider,setProvider]=useState('brevo'),[sender,setSender]=useState(''),[key,setKey]=useState('');
 async function load(q=''){try{const r=await fetch('/api/admin?q='+encodeURIComponent(q),{cache:'no-store'}),d=await r.json() as Dashboard;if(!r.ok)throw new Error(d.error||'Could not load dashboard.');setData(d);if(d.email){setProvider(d.email.provider);setSender(d.email.sender);}setError('');}catch(e){setError(e instanceof Error?e.message:'Retry loading.');}}
 useEffect(()=>{void load();},[]);
 async function action(body:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json() as Dashboard;if(!r.ok)throw new Error(d.error||'Action failed.');if(body.action==='save-email')setKey('');setNotice(d.message||'Saved.');await load(query);}catch(e){setError(e instanceof Error?e.message:'Retry.');}finally{setBusy(false);}}
 const owner=data?.role==='super_admin';
 return <main className="min-h-screen bg-background px-4 py-6 text-foreground sm:px-8"><div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><a href="/" className="text-sm underline">← WoxRadar</a><h1 className="mt-3 text-3xl font-bold">Campus administration</h1><p className="mt-2 text-base">{data?(owner?'Super Admin · Raja':'Admin · Moderation team'):'Checking admin access…'}</p></div><Button variant="outline" disabled={busy} onClick={()=>load(query)}>Refresh</Button></header>
 {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-green-50 p-4 text-green-900">{notice}</p>}
 {data&&<><section className="grid grid-cols-2 gap-3 lg:grid-cols-5">{Object.entries(data.summary).map(([label,value])=><div key={label} className="rounded-2xl border bg-card p-5"><p className="text-sm capitalize">{label==='reports'?'Open reports':label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>)}</section>
 <Tabs defaultValue={owner?'email':'moderation'}><TabsList className="h-auto flex-wrap justify-start gap-2"><TabsTrigger value="moderation">Moderation</TabsTrigger><TabsTrigger value="people">Students & admins</TabsTrigger><TabsTrigger value="logs">Activity log</TabsTrigger>{owner&&<TabsTrigger value="email">Email setup</TabsTrigger>}</TabsList>
 <TabsContent value="moderation"><Moderation/></TabsContent>
 <TabsContent value="people" className="space-y-4"><form className="flex flex-col gap-3 sm:flex-row" onSubmit={(e:FormEvent)=>{e.preventDefault();void load(query);}}><Input aria-label="Search students by name or email" placeholder="Search name or email" value={query} onChange={e=>setQuery(e.target.value)}/><Button className="w-full sm:w-auto">Search</Button></form><p className="text-sm">Up to 50 students. Admins can review reports; only you can manage roles and email settings.</p>{data.users.map(u=><article key={u.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-card p-4"><div><p className="font-bold">{u.name} · {u.email==='rajavreddy.g@gmail.com'?'Super Admin':u.admin?'Admin':'Student'}</p><p className="break-all text-sm">{u.email}</p><p className="text-sm">{u.school} · {u.year}</p></div>{owner&&u.email!=='rajavreddy.g@gmail.com'&&<Button variant="outline" disabled={busy} onClick={()=>action({action:u.admin?'revoke-admin':'grant-admin',userId:u.id})}>{u.admin?'Remove admin role':'Make admin'}</Button>}</article>)}{!data.users.length&&<p>No students match this search.</p>}</TabsContent>
 <TabsContent value="logs"><div className="space-y-3">{data.logs.map((l,i)=><article key={i} className="rounded-xl border bg-card p-4 text-sm"><p className="font-semibold">{l.action}</p><p className="break-all">{l.actor} · {new Date(l.createdAt).toLocaleString()}</p><p className="break-all text-muted-foreground">Target: {l.target}</p></article>)}{!data.logs.length&&<p className="p-5">Admin actions will appear here.</p>}</div></TabsContent>
 {owner&&<TabsContent value="email"><form className="max-w-2xl space-y-5 rounded-2xl border bg-card p-6" onSubmit={e=>{e.preventDefault();void action({action:'save-email',provider,sender,key});}}><h2 className="text-xl font-bold">College verification email</h2><p className="text-base">{data.email?.configured?'An API key is saved. Leave the key field blank to keep it.':'Connect Brevo or Resend to send student verification codes.'}</p><label className="block space-y-2"><span>Provider</span><select className="block min-h-11 w-full rounded-lg border bg-background px-3" value={provider} onChange={e=>setProvider(e.target.value)}><option value="brevo">Brevo</option><option value="resend">Resend</option></select></label><label className="block space-y-2"><span>Verified sender email</span><Input type="email" required value={sender} onChange={e=>setSender(e.target.value)} placeholder="Your provider-approved sender address"/></label><label className="block space-y-2"><span>API key</span><Input type="password" autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value)} placeholder={data.email?.configured?'Key saved · enter a replacement if needed':'Paste your API key here'}/></label><p className="text-sm text-muted-foreground">Your key is encrypted on the server and is never returned to this page. Admins cannot access email settings.</p>{!data.email?.storageReady&&<p role="alert">Secure storage needs configuration before saving.</p>}<div className="flex flex-wrap gap-3"><Button disabled={busy||!data.email?.storageReady} type="submit">{busy?'Working…':'Save email settings'}</Button><Button type="button" variant="outline" disabled={busy||!data.email?.configured} onClick={()=>action({action:'test-email'})}>Check provider connection</Button></div><p className="text-sm">The connection check sends no email. After saving, request a code from My profile to test delivery to your Woxsen inbox.</p></form></TabsContent>}
 </Tabs></>}
 </div></main>;
}
