"use client";
import {useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
type ApiResponse={error?:string;verified:boolean;collegeEmail:string;senderConfigured:boolean};
export function CollegeVerification({initialEmail,onVerified}:{initialEmail:string;onVerified:(email:string)=>void}){
  const[email,setEmail]=useState(initialEmail.endsWith("@woxsen.edu.in")?initialEmail:""),[verified,setVerified]=useState(false),[configured,setConfigured]=useState<boolean|null>(null),[sent,setSent]=useState(false),[code,setCode]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[resendAt,setResendAt]=useState(0),[clock,setClock]=useState(Date.now());
  useEffect(()=>{let active=true;fetch("/api/verification",{cache:"no-store"}).then(async r=>{const d=await r.json() as ApiResponse;if(!r.ok)throw new Error(d.error);if(active){setConfigured(d.senderConfigured);if(d.verified){setVerified(true);setEmail(d.collegeEmail);onVerified(d.collegeEmail);}}}).catch(e=>{if(active)setError(e.message??"Could not load verification.");});return()=>{active=false;};},[]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(resendAt<=Date.now())return;const t=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(t);},[resendAt]);
  async function submit(action:"send"|"verify"){setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/verification",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,email,code})}),d=await r.json() as ApiResponse;if(!r.ok)throw new Error(d.error);if(d.verified){setVerified(true);setEmail(d.collegeEmail);onVerified(d.collegeEmail);setCode("");}else{setSent(true);setResendAt(Date.now()+60000);setClock(Date.now());setMessage("Code sent. Check your college inbox and spam folder. It expires in 10 minutes.");}}catch(e){setError(e instanceof Error?e.message:"Retry.");}finally{setBusy(false);}}
  const wait=Math.max(0,Math.ceil((resendAt-clock)/1000)),input="min-h-11 rounded-xl border bg-white p-3 text-base";
  return <section className="rounded-2xl border border-[#D9E0CD] bg-white p-5 sm:p-6"><h2 className="text-lg font-bold">Verify your college email</h2>{verified?<p role="status" className="mt-3 break-all text-base text-[#315E33]">Verified: {email}</p>:<><p className="mt-2 text-base leading-6 text-[#607767]">Use your @woxsen.edu.in inbox to access campus posts, circles, and introductions. You can save a draft before verifying.</p><label className="mt-4 grid gap-2 text-sm font-semibold">College email<input type="email" autoComplete="email" value={email} onChange={e=>{setEmail(e.target.value);setSent(false);setCode("");}} placeholder="you@woxsen.edu.in" disabled={busy} className={input}/></label><Button className="mt-3 bg-[#17392B] text-white" disabled={busy||configured===false||wait>0||!email} onClick={()=>submit("send")}>{busy?"Please wait…":wait?`Resend in ${wait}s`:sent?"Send a new code":"Send verification code"}</Button>{sent&&<div className="mt-4"><label className="grid gap-2 text-sm font-semibold">Six-digit code<input inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} maxLength={6} className={input}/></label><Button className="mt-3" disabled={busy||code.length!==6} onClick={()=>submit("verify")}>Verify email</Button></div>}{configured===false&&<p role="status" className="mt-3 rounded-xl bg-[#FFFBEA] p-3 text-sm">The pilot email sender is being set up. Save your draft and return when verification opens.</p>}</>}{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}{message&&<p role="status" className="mt-3 text-sm text-[#315E33]">{message}</p>}<p className="mt-3 text-sm text-[#607767]">Your college email stays private. Verification proves inbox access, not your course or age.</p></section>;
}
