"use client";
import {useCallback,useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
type Message={id:string;senderUserId:string;body:string;createdAt:number};
type ApiResponse={error?:string;messages?:Message[];viewerUserId:string};
export function ConnectionChat({requestId,otherUserId}:{requestId:string;otherUserId:string}){const[messages,setMessages]=useState<Message[]>([]),[viewer,setViewer]=useState(""),[body,setBody]=useState(""),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState(""),[blocked,setBlocked]=useState(false),[reportId,setReportId]=useState(""),[reason,setReason]=useState("");
 const load=useCallback(async()=>{setError("");try{const r=await fetch(`/api/messages?requestId=${encodeURIComponent(requestId)}`,{cache:"no-store"}),d=await r.json() as ApiResponse;if(!r.ok)throw new Error(d.error);setMessages(d.messages??[]);setViewer(d.viewerUserId);}catch(e){setError(e instanceof Error?e.message:"Retry.");}finally{setLoading(false);}},[requestId]);
 useEffect(()=>{void load();},[load]);
 async function send(){setSending(true);setError("");try{const r=await fetch("/api/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId,body})}),d=await r.json() as ApiResponse;if(!r.ok)throw new Error(d.error);setBody("");await load();}catch(e){setError(e instanceof Error?e.message:"Retry.");}finally{setSending(false);}}
 async function safety(kind:"block"|"report"){setSending(true);setError("");try{const r=await fetch("/api/safety",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(kind==="block"?{kind,targetUserId:otherUserId}:{kind,targetType:"message",targetId:reportId,reason})}),d=await r.json() as ApiResponse;if(!r.ok)throw new Error(d.error);if(kind==="block"){setBlocked(true);setMessages([]);setBody("");}else{setReportId("");setReason("");}}catch(e){setError(e instanceof Error?e.message:"Retry.");}finally{setSending(false);}}
 if(blocked)return <p role="status" className="mt-4 rounded-xl bg-[#F5F8F0] p-4 text-base">Student blocked. This conversation and contact sharing are no longer accessible.</p>;
 return <section className="mt-4 rounded-xl border bg-white p-4"><div className="flex items-center justify-between gap-3"><h4 className="text-base font-bold">Your conversation</h4><Button variant="outline" disabled={sending} onClick={load}>Refresh</Button></div><p className="mt-2 text-sm text-[#607767]">Only you two can read this conversation. Refresh to check for replies. Contacts can stay private.</p><div className="mt-4 max-h-72 space-y-3 overflow-y-auto" aria-live="polite">{loading?<p role="status">Loading…</p>:messages.length?messages.map(m=><article key={m.id} className={"rounded-xl p-3 "+(m.senderUserId===viewer?"ml-6 bg-[#EAF5D0]":"mr-6 bg-[#F5F8F0]")}><p className="text-sm font-semibold">{m.senderUserId===viewer?"You":"Your connection"}</p><p className="mt-1 whitespace-pre-wrap break-words text-base">{m.body}</p><time className="mt-1 block text-sm text-[#607767]">{new Date(m.createdAt).toLocaleString()}</time>{m.senderUserId!==viewer&&<button type="button" className="mt-2 min-h-11 text-sm underline" onClick={()=>setReportId(m.id)}>Report message</button>}</article>):<p className="text-sm">Start with something you both enjoy.</p>}</div><label className="mt-4 grid gap-2 text-sm font-semibold">Message<textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={800} rows={3} className="rounded-xl border bg-white p-3 text-base"/></label><div className="mt-2 flex items-center justify-between"><span className="text-sm">{body.length}/800</span><Button disabled={sending||!body.trim()} onClick={send}>{sending?"Sending…":"Send message"}</Button></div><Button variant="outline" className="mt-3" disabled={sending} onClick={()=>{if(window.confirm("Block this student and stop this conversation?"))void safety("block");}}>Block student</Button>{reportId&&<div className="mt-4 rounded-xl border p-3"><label className="grid gap-2 text-sm font-semibold">Why should this message be reviewed?<textarea maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} className="rounded-xl border p-3 text-base"/></label><div className="mt-3 flex gap-3"><Button variant="outline" onClick={()=>setReportId("")}>Cancel</Button><Button disabled={sending||reason.trim().length<8} onClick={()=>safety("report")}>Submit report</Button></div></div>}{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}</section>;
}
