"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, BarChart3, Bell, CalendarDays, ChevronRight, CircleUserRound, Compass, Handshake, MapPin, MessageCircle, Search, Send, Sparkles, Ticket, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { CirclesView } from "./circles";
import type { CircleMembership } from "./circles";
import { ProfileView } from "./profile";
import type { StudentProfile } from "./profile";
import { MatchesView } from "./matches";
import { RequestsView } from "./requests";
import { ImpactView } from "./impact";
import { PostDetail } from "./post-detail";
import type { DetailPost } from "./post-detail";
import { SignInPanel } from "./sign-in-panel";

type Post = DetailPost;
type PostComment = { id:string; postId:string; authorName:string; authorInitials:string; body:string; createdAt:number };
type InteractionSummary = { commentCount:number; reactions:Record<string,number>; myReactions:string[] };
type PageResponse = {error?:string;profile?:StudentProfile;posts?:Post[];summaries?:Record<string,InteractionSummary>;comments?:PostComment[];comment:PostComment;post:Post};

const reactionOptions = ["👍", "❤️", "🎉", "🤝"];
const emptySummary = ():InteractionSummary => ({commentCount:0,reactions:{},myReactions:[]});
const initialPosts:Post[] = [
  {id:"a1",type:"Activity",title:"Designing with AI: maker session",detail:"Bring one unfinished idea. Leave with a small prototype and new collaborators.",time:"Fri · 4:30 PM",place:"Innovation Lab · Block C",tags:["AI","Design","Build"],accent:"lime",count:7},
  {id:"a2",type:"Opportunity",title:"Hackathon team call: climate data",detail:"Two more people needed for data, product or frontend before Saturday's shortlist.",time:"Deadline · Thu",place:"Open to all schools",tags:["Hackathon","Data","Team"],accent:"coral"},
  {id:"a3",type:"Exchange",title:"Scientific calculator, available to borrow",detail:"Casio fx-991ES Plus. Free to borrow until Monday afternoon.",time:"Available now",place:"Library pickup",tags:["Borrow","Academic"],accent:"blue"},
  {id:"a4",type:"Gig",title:"Need an event photographer for Saturday",detail:"Two hours at the entrepreneurship mixer. Paid student gig; send a portfolio link.",time:"Sat · 5:00 PM",place:"Central Quad",tags:["Photography","Paid"],accent:"purple"},
];
function chipClass(accent:string) { return ({lime:"bg-[#D8FF48] text-[#173218]",coral:"bg-[#FFD9D2] text-[#7A281E]",blue:"bg-[#D7ECFF] text-[#164673]",purple:"bg-[#EADFff] text-[#56338E]"} as Record<string,string>)[accent] ?? "bg-slate-100 text-slate-700"; }

export default function Home() {
  const [tab,setTab]=useState("explore"), [query,setQuery]=useState(""), [filter,setFilter]=useState("All");
  const [posts,setPosts]=useState<Post[]>(initialPosts);
  const [circleMemberships,setCircleMemberships]=useState<CircleMembership[]>([]);
  const [selected,setSelected]=useState<Post>(initialPosts[0]), [invite,setInvite]=useState<string|null>(null), [requestRefresh,setRequestRefresh]=useState(0), [composerOpen,setComposerOpen]=useState(false);
  const [requestCount,setRequestCount]=useState(0);
  const [form,setForm]=useState({type:"Activity",title:"",detail:"",time:"",place:"",tags:""});
  const [formError,setFormError]=useState("");
  const [interactions,setInteractions]=useState<Record<string,InteractionSummary>>({});
  const [threadPost,setThreadPost]=useState<Post|null>(null);
  const [detailPost,setDetailPost]=useState<Post|null>(null);
  const [comments,setComments]=useState<PostComment[]>([]);
  const [commentsLoading,setCommentsLoading]=useState(false);
  const [commentBody,setCommentBody]=useState("");
  const [commentSubmitting,setCommentSubmitting]=useState(false);
  const [reactionBusy,setReactionBusy]=useState<string|null>(null);
  const [interactionError,setInteractionError]=useState("");
  const [viewer,setViewer]=useState<StudentProfile|null>(null);
  const [viewerLoading,setViewerLoading]=useState(true);
  const [viewerError,setViewerError]=useState("");
  const loadViewer=async()=>{setViewerLoading(true);setViewerError("");try{const response=await fetch("/api/profile",{cache:"no-store"});const data=await response.json() as PageResponse;if(response.status===401){setViewer(null);setTab("profile");return;}if(!response.ok||!data.profile)throw new Error(data.error??"Could not load your account.");setViewer(data.profile);if(!data.profile.profileCompleted||new URLSearchParams(window.location.search).has("setup"))setTab("profile");}catch(e){setViewerError(e instanceof Error?e.message:"Could not load your account.");}finally{setViewerLoading(false);}};
  useEffect(()=>{void loadViewer();},[]);
  const updateSummary=(postId:string,data:{summaries?:Record<string,InteractionSummary>})=>{if(data.summaries?.[postId])setInteractions(current=>({...current,[postId]:data.summaries![postId]}));};
  const toggleReaction=async(post:Post,emoji:string)=>{setInteractionError("");setReactionBusy(`${post.id}:${emoji}`);try{const response=await fetch("/api/interactions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"reaction",postId:post.id,emoji})});const data=await response.json() as PageResponse;if(!response.ok)throw new Error(data.error??"Could not save your reaction.");updateSummary(post.id,data);}catch(reason){setInteractionError(reason instanceof Error?reason.message:"Could not save your reaction.");}finally{setReactionBusy(null);}};
  const openComments=async(post:Post)=>{setThreadPost(post);setComments([]);setCommentBody("");setInteractionError("");setCommentsLoading(true);try{const response=await fetch(`/api/interactions?postId=${encodeURIComponent(post.id)}`);const data=await response.json() as PageResponse;if(!response.ok)throw new Error(data.error??"Could not load comments.");setComments(data.comments??[]);updateSummary(post.id,data);}catch(reason){setInteractionError(reason instanceof Error?reason.message:"Could not load comments.");}finally{setCommentsLoading(false);}};
  const submitComment=async()=>{if(!threadPost)return;setInteractionError("");setCommentSubmitting(true);try{const response=await fetch("/api/interactions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"comment",postId:threadPost.id,body:commentBody})});const data=await response.json() as PageResponse;if(!response.ok)throw new Error(data.error??"Could not post your comment.");setComments(current=>[...current,data.comment]);setCommentBody("");updateSummary(threadPost.id,data);}catch(reason){setInteractionError(reason instanceof Error?reason.message:"Could not post your comment.");}finally{setCommentSubmitting(false);}};
  const filtered = useMemo(()=>posts.filter(p => (filter==="All"||p.type===filter) && (`${p.title} ${p.detail} ${p.tags.join(" ")}`).toLowerCase().includes(query.toLowerCase())),[filter,query,posts]);
  const openMatches=(post:Post)=>{setSelected(post);setTab("matches");fetch("/api/impact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventName:"match_open",contextId:post.id})}).catch(()=>undefined);};
  useEffect(()=>{if(!viewer?.profileCompleted)return;fetch("/api/posts").then(async r=>{const d=await r.json() as PageResponse;if(r.ok&&d.posts?.length){const loaded=d.posts.map((p:Post & {tags:string|string[]})=>({...p,tags:typeof p.tags==="string"?JSON.parse(p.tags):p.tags}));setPosts(loaded);const a=loaded.find(p=>p.type==="Activity"&&p.status!=="closed");if(a)setSelected(a);}}).catch(()=>undefined);fetch("/api/interactions").then(r=>r.ok?r.json() as Promise<PageResponse>:null).then(data=>{if(data?.summaries)setInteractions(data.summaries);}).catch(()=>undefined);fetch("/api/impact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventName:"feed_view"})}).catch(()=>undefined);},[viewer?.profileCompleted]);
  if (viewerLoading) return <main className="grid min-h-screen place-items-center bg-[#F7F9F2] p-6 text-sm text-[#58705F]">Loading WoxRadar…</main>;
  if (!viewer) return <main className="min-h-screen bg-[#F4F7EE] px-4 py-10 sm:py-16"><SignInPanel/></main>;
  if (!viewer.profileCompleted || !viewer.collegeVerified) return <main className="min-h-screen bg-[#F7F9F2] px-4 py-6 sm:px-6 sm:py-10"><div className="mx-auto max-w-3xl"><ProfileView profile={viewer} loading={false} onProfileChange={setViewer}/></div></main>;
  return <main className="min-h-screen bg-[#F7F9F2] text-[#112117]"><div className="mx-auto max-w-[1500px] px-4 py-4 sm:px-6 lg:px-8">
    <header className="flex min-w-0 items-center justify-between gap-3 rounded-[1.35rem] border border-[#D9E0CD] bg-white px-4 py-3 shadow-[0_16px_40px_rgba(34,55,34,0.06)] sm:px-5">
      <button onClick={()=>setTab("explore")} className="flex min-w-0 shrink-0 items-center gap-3 text-left" aria-label="Go to WoxRadar explore"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-[#152D25] text-[#D8FF48]"><Compass className="size-5"/></span><span className="min-w-0"><strong className="block text-lg leading-5 tracking-[-0.04em]">WoxRadar</strong><span className="block truncate text-xs leading-5 text-[#63806C]">Campus, with context</span></span></button>
      <div className="hidden items-center gap-2 rounded-full border border-[#E2E8DA] bg-[#F7F9F2] px-3 py-2 md:flex"><Search className="size-4 text-[#63806C]"/><input value={query} onChange={e=>{setQuery(e.target.value);setTab("explore");}} className="w-56 bg-transparent text-sm outline-none placeholder:text-[#86A08D]" placeholder="Search campus posts…"/></div>
      <div className="flex shrink-0 items-center gap-2"><button onClick={()=>setTab("requests")} className="relative grid size-9 place-items-center rounded-xl border border-[#E2E8DA] text-[#45604E]" aria-label={`Open invitations${requestCount ? `, ${requestCount} pending` : ""}`}><Bell className="size-4"/>{requestCount?<span className="absolute -right-1 -top-1 grid min-w-4 place-items-center rounded-full bg-[#D8FF48] px-1 text-[10px] font-bold text-[#17392B]">{requestCount}</span>:null}</button><button onClick={()=>setTab("profile")} className="grid size-9 place-items-center rounded-xl bg-[#17392B] text-xs font-semibold text-white" aria-label="Open your profile">{viewer?.initials??"?"}</button></div>
    </header>
    {viewerError?<div role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{viewerError} <Button variant="outline" onClick={()=>void loadViewer()} disabled={viewerLoading}>Retry account loading</Button></div>:null}
    <Tabs value={tab} onValueChange={setTab} className="mt-5 gap-5 xl:grid xl:grid-cols-[220px_minmax(0,1fr)_290px]">
      <aside className="hidden self-start rounded-[1.35rem] border border-[#D9E0CD] bg-white p-3 xl:block"><p className="px-3 pb-2 pt-1 text-xs font-bold uppercase tracking-[0.12em] text-[#77907C]">Navigate</p><TabsList variant="line" className="!h-auto w-full flex-col items-stretch gap-1 p-0"><Nav value="explore" icon={<Compass/>} label="Explore"/><Nav value="circles" icon={<UsersRound/>} label="Circles" count={circleMemberships.filter(item=>item.state==="accepted").length}/><Nav value="matches" icon={<UsersRound/>} label="Find people"/><Nav value="requests" icon={<MessageCircle/>} label="Requests" count={requestCount}/><Nav value="profile" icon={<CircleUserRound/>} label="My profile"/><Nav value="impact" icon={<BarChart3/>} label="Pilot impact"/></TabsList><div className="mt-5 rounded-2xl bg-[#17392B] p-4 text-white"><Sparkles className="mb-3 size-5 text-[#D8FF48]"/><p className="text-sm font-semibold leading-5">Try the campus demo</p><p className="mt-2 text-xs leading-5 text-[#C4D7C8]">Example content is labelled. Publish a real activity to match with consenting pilot members.</p></div></aside>
      <section className="min-w-0"><div className="mb-5 overflow-x-auto xl:hidden"><TabsList className="flex h-auto min-h-11 w-max min-w-full rounded-xl"><TabsTrigger value="explore">Explore</TabsTrigger><TabsTrigger value="circles">Circles</TabsTrigger><TabsTrigger value="matches">People</TabsTrigger><TabsTrigger value="requests">Requests</TabsTrigger><TabsTrigger value="profile">Profile</TabsTrigger><TabsTrigger value="impact">Impact</TabsTrigger></TabsList></div>
        <TabsContent value="explore" className="mt-0"><Explore posts={filtered} filter={filter} setFilter={setFilter} onSelect={post=>{setSelected(post);setDetailPost(post);}} onMatch={openMatches} onCompose={()=>viewer?setComposerOpen(true):setTab("profile")} interactions={interactions} onReact={toggleReaction} onComments={openComments} interactionError={interactionError} reactionBusy={reactionBusy}/></TabsContent>
        <TabsContent value="circles" className="mt-0"><CirclesView currentUser={viewer} memberships={circleMemberships} onMembershipsChange={setCircleMemberships}/></TabsContent>
        <TabsContent value="matches" className="mt-0"><MatchesView key={selected.id + ":" + String(viewer?.discoveryEnabled) + ":" + String(viewer?.profileCompleted)} activity={selected} viewer={viewer} invite={invite} onOpenProfile={()=>setTab("profile")} onInvite={async(name,userId,openingMessage)=>{const response=await fetch("/api/requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recipientName:name,recipientUserId:userId,openingMessage,postId:selected.id,activityTitle:selected.title})});const data=await response.json() as PageResponse;if(!response.ok)throw new Error(data.error??"Could not send the invitation.");setInvite(name);setRequestRefresh(value=>value+1);}}/></TabsContent>
        <TabsContent value="requests" className="mt-0"><RequestsView refreshKey={requestRefresh} onExplore={()=>setTab("explore")} onCountChange={setRequestCount}/></TabsContent>
        <TabsContent value="profile" className="mt-0">{viewer?.isModerator&&<a href="/admin" className="mb-4 inline-block min-h-11 rounded-xl border bg-white px-4 py-3 text-sm font-semibold underline">Admin dashboard</a>}{viewerError?<p className="rounded-xl bg-white p-6 text-sm">Your saved introduction is unavailable. Use Retry account loading above.</p>:<ProfileView profile={viewer} loading={viewerLoading} onProfileChange={p=>{setViewer(p);setRequestRefresh(n=>n+1);}} onExplore={()=>setTab("explore")}/>}</TabsContent>
        <TabsContent value="impact" className="mt-0"><ImpactView/></TabsContent>
      </section>
      <aside className="hidden self-start space-y-4 xl:block"><section className="rounded-[1.35rem] border border-[#D9E0CD] bg-white p-5"><p className="text-xs font-bold uppercase tracking-[0.1em] text-[#77907C]">This week</p><h2 className="mt-2 text-xl font-bold tracking-[-0.04em]">Make one useful connection.</h2><p className="mt-2 text-sm leading-6 text-[#58705F]">Choose an activity first, then see people who opted in to join it.</p><div className="mt-5 flex items-center gap-3 border-t border-[#E8EDE2] pt-4"><span className="grid size-9 place-items-center rounded-xl bg-[#EAF5D0] text-[#2D5A30]"><Handshake className="size-4"/></span><span className="text-sm"><b>1</b> new intro this week<br/><span className="text-xs text-[#78907F]">A simple starting goal</span></span></div></section><section className="rounded-[1.35rem] border border-[#D9E0CD] bg-white p-5"><div className="flex items-center justify-between"><p className="text-sm font-semibold">Quick filters</p><Ticket className="size-4 text-[#77907C]"/></div><div className="mt-3 flex flex-wrap gap-2">{["Hackathons","Clubs","Borrow","Paid gigs"].map(tag=><button key={tag} onClick={()=>{setQuery(tag);setTab("explore");}} className="rounded-full bg-[#F1F4EB] px-3 py-1.5 text-xs font-medium text-[#43604B] hover:bg-[#E6EEDF]">{tag}</button>)}</div></section></aside>
    </Tabs></div>
    <PostDetail post={detailPost} viewer={viewer} onClose={()=>setDetailPost(null)} onMatch={openMatches} onComments={openComments} onPostChange={updated=>{setDetailPost(updated);setPosts(current=>current.map(post=>post.id===updated.id?updated:post));if(selected.id===updated.id)setSelected(updated);}}/>
    <Dialog open={composerOpen} onOpenChange={setComposerOpen}><DialogContent><DialogHeader><DialogTitle>Post to WoxRadar</DialogTitle><DialogDescription>Add one specific activity, opportunity, exchange listing, or small gig. Your post will be visible to verified pilot students.</DialogDescription></DialogHeader><div className="grid gap-3"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className="h-10 rounded-lg border bg-white px-3 text-sm"><option>Activity</option><option>Opportunity</option><option>Exchange</option><option>Gig</option></select><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="h-10 rounded-lg border bg-white px-3 text-sm" placeholder="Title"/><textarea value={form.detail} onChange={e=>setForm({...form,detail:e.target.value})} className="min-h-24 rounded-lg border bg-white p-3 text-sm" placeholder="What should someone know before acting?"/><div className="grid gap-3 sm:grid-cols-2"><input value={form.time} onChange={e=>setForm({...form,time:e.target.value})} className="h-10 rounded-lg border bg-white px-3 text-sm" placeholder="Date, time or deadline"/><input value={form.place} onChange={e=>setForm({...form,place:e.target.value})} className="h-10 rounded-lg border bg-white px-3 text-sm" placeholder="Venue or pickup area"/></div><input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} className="h-10 rounded-lg border bg-white px-3 text-sm" placeholder="Tags, separated by commas"/>{formError?<p className="text-sm text-red-700">{formError}</p>:null}</div><DialogFooter><Button variant="outline" onClick={()=>setComposerOpen(false)}>Close</Button><Button onClick={async()=>{setFormError("");const response=await fetch("/api/posts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,tags:form.tags.split(",").map(tag=>tag.trim()).filter(Boolean)})});const data=await response.json() as PageResponse;if(!response.ok){setFormError(data.error??"Could not save the post.");return;}setPosts([data.post,...posts]);setSelected(data.post);setForm({type:"Activity",title:"",detail:"",time:"",place:"",tags:""});setComposerOpen(false);}} className="bg-[#17392B] text-white hover:bg-[#244A39]">Publish post</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(threadPost)} onOpenChange={open=>{if(!open){setThreadPost(null);setInteractionError("");}}}><DialogContent className="max-h-[88vh] overflow-hidden sm:max-w-xl"><DialogHeader><DialogTitle>Comments</DialogTitle><DialogDescription>{threadPost?.title}</DialogDescription></DialogHeader><div className="max-h-[48vh] space-y-3 overflow-y-auto pr-1">{commentsLoading?<p className="rounded-xl bg-[#F5F8F0] p-4 text-sm text-[#607767]">Loading conversation…</p>:comments.length?comments.map(comment=><article key={comment.id} className="flex gap-3 rounded-xl bg-[#F5F8F0] p-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#17392B] text-xs font-bold text-white">{comment.authorInitials}</span><div className="min-w-0"><div className="flex flex-wrap items-baseline gap-x-2"><p className="text-sm font-bold">{comment.authorName}</p><time className="text-xs text-[#78907F]">{new Date(Number(comment.createdAt)).toLocaleString([], {month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</time></div><p className="mt-1 whitespace-pre-wrap break-words text-sm leading-6 text-[#48604F]">{comment.body}</p></div></article>):<div className="rounded-xl border border-dashed border-[#C7D6BD] p-6 text-center"><MessageCircle className="mx-auto size-6 text-[#89A378]"/><p className="mt-2 text-sm font-bold">Start the conversation</p><p className="mt-1 text-xs text-[#607767]">Ask a useful question or share something others should know.</p></div>}</div><div className="border-t pt-4"><label htmlFor="post-comment" className="text-sm font-bold">Add a comment</label><textarea id="post-comment" value={commentBody} onChange={event=>setCommentBody(event.target.value)} maxLength={400} className="mt-2 min-h-20 w-full rounded-xl border bg-white p-3 text-sm outline-none focus:ring-2 focus:ring-[#8AA470]" placeholder="Write your comment…"/><div className="mt-2 flex items-center justify-between gap-3"><span className="text-xs text-[#78907F]">{commentBody.length}/400</span><Button onClick={submitComment} disabled={!commentBody.trim()||commentSubmitting} className="bg-[#17392B] text-white hover:bg-[#244A39]"><Send/> {commentSubmitting?"Posting…":"Comment"}</Button></div>{interactionError?<p role="alert" className="mt-2 text-sm text-red-700">{interactionError}</p>:null}</div></DialogContent></Dialog>
  </main>;
}
function Nav({value,icon,label,count}:{value:string;icon:React.ReactNode;label:string;count?:number}) { return <TabsTrigger value={value} className="!h-auto min-h-11 w-full flex-none justify-start rounded-xl px-3 py-2.5 text-sm leading-5 data-[state=active]:bg-[#EAF5D0] data-[state=active]:text-[#17392B]"><span className="grid size-5 shrink-0 place-items-center">{icon}</span><span className="min-w-0 truncate">{label}</span>{count?<span className="ml-auto rounded-full bg-[#D8FF48] px-2 py-0.5 text-[11px] font-bold text-[#17392B]">{count}</span>:null}</TabsTrigger>; }
function Explore({posts,filter,setFilter,onSelect,onMatch,onCompose,interactions,onReact,onComments,interactionError,reactionBusy}:{posts:Post[];filter:string;setFilter:(v:string)=>void;onSelect:(p:Post)=>void;onMatch:(p:Post)=>void;onCompose:()=>void;interactions:Record<string,InteractionSummary>;onReact:(p:Post,emoji:string)=>void;onComments:(p:Post)=>void;interactionError:string;reactionBusy:string|null}) { return <div className="space-y-5"><section className="relative overflow-hidden rounded-[1.5rem] bg-[#17392B] p-6 text-white sm:p-8"><div className="relative z-10 max-w-xl"><p className="text-xs font-bold uppercase tracking-[0.13em] text-[#D8FF48]">Woxsen University · Pilot</p><h1 className="mt-3 text-3xl font-bold tracking-[-0.055em] sm:text-4xl">Do more than notice what is happening.</h1><p className="mt-3 max-w-lg text-sm leading-6 text-[#C4D7C8] sm:text-base">Find the next campus activity that fits you, then make it easier to show up with someone new.</p><div className="mt-5 flex flex-wrap gap-3"><Button onClick={()=>posts[0]&&onMatch(posts[0])} disabled={!posts.length} className="bg-[#D8FF48] text-[#17392B] hover:bg-[#C8F23C]"><UsersRound/> Find someone to go with</Button><Button onClick={onCompose} variant="outline" className="border-white/30 bg-white/5 text-white hover:bg-white/10 hover:text-white"><Send/> Post something</Button></div></div><div className="absolute -right-14 -top-14 size-60 rounded-full border-[32px] border-[#D8FF48]/20"/><div className="absolute bottom-7 right-8 hidden rounded-2xl border border-white/15 bg-white/10 p-4 backdrop-blur sm:block"><p className="text-2xl font-bold">{posts.length}</p><p className="text-xs text-[#C4D7C8]">open campus posts</p></div></section>
  {interactionError?<p role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{interactionError}</p>:null}
  <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-[#58705F]">Today at Woxsen</p><h2 className="text-2xl font-bold tracking-[-0.04em]">Explore with a reason to act</h2></div><div className="flex flex-wrap gap-2">{["All","Activity","Opportunity","Exchange","Gig"].map(item=><button key={item} onClick={()=>setFilter(item)} className={`rounded-full px-3 py-2 text-xs font-semibold transition ${filter===item?"bg-[#17392B] text-white":"border border-[#D9E0CD] bg-white text-[#55705C] hover:border-[#A7BC9A]"}`}>{item}</button>)}</div></div>
  <div className="grid gap-3 sm:grid-cols-2">{posts.map(post=>{const summary=interactions[post.id]??emptySummary();const closed=post.status==="closed";return <article key={post.id} className={`group rounded-[1.25rem] border border-[#D9E0CD] bg-white p-5 shadow-[0_8px_22px_rgba(34,55,34,0.035)] ${closed?"opacity-75":""}`}><div className="flex items-start justify-between gap-3"><div className="flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${chipClass(post.accent)}`}>{post.type}</span>{closed?<span className="rounded-full bg-[#ECEFEB] px-2.5 py-1 text-[11px] font-bold text-[#617065]">Closed</span>:null}</div><button onClick={()=>onSelect(post)} aria-label={`Open ${post.title}`} className="grid size-8 place-items-center rounded-lg bg-[#F2F5EC] text-[#47614E] hover:bg-[#E4EBD9]"><ArrowUpRight className="size-4"/></button></div><h3 className="mt-4 text-lg font-bold leading-6 tracking-[-0.03em]">{post.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-5 text-[#607767]">{post.detail}</p><div className="mt-4 space-y-2 text-xs font-medium text-[#516A59]"><p className="flex gap-2"><CalendarDays className="size-3.5 text-[#85A06A]"/>{post.time}</p><p className="flex gap-2"><MapPin className="size-3.5 text-[#85A06A]"/>{post.place}</p></div><div className="mt-4 flex flex-wrap gap-1.5">{post.tags.map(tag=><span key={tag} className="rounded-md bg-[#F1F4EB] px-2 py-1 text-[11px] text-[#57705D]">{tag}</span>)}</div><div className="mt-4 flex flex-wrap items-center gap-1.5 border-t border-[#E8EDE2] pt-3">{reactionOptions.map(emoji=>{const active=summary.myReactions.includes(emoji);const count=summary.reactions[emoji]??0;const busy=reactionBusy===`${post.id}:${emoji}`;return <button key={emoji} type="button" disabled={busy} onClick={()=>onReact(post,emoji)} aria-label={`${active?"Remove":"Add"} ${emoji} reaction`} aria-pressed={active} className={`inline-flex min-h-9 items-center gap-1 rounded-full border px-2.5 text-sm transition disabled:opacity-60 ${active?"border-[#9BB77A] bg-[#EAF5D0]":"border-[#D9E0CD] bg-white hover:bg-[#F5F8F0]"}`}><span aria-hidden="true">{emoji}</span>{count>0?<span className="text-xs font-bold text-[#48604F]">{count}</span>:null}</button>})}<button type="button" onClick={()=>onComments(post)} className="ml-auto inline-flex min-h-9 items-center gap-1.5 rounded-full px-2.5 text-xs font-bold text-[#48604F] hover:bg-[#F1F4EB]"><MessageCircle className="size-4"/>{summary.commentCount} {summary.commentCount===1?"comment":"comments"}</button></div>{post.type==="Activity"&&!closed?<Button onClick={()=>onMatch(post)} variant="outline" className="mt-4 w-full border-[#BFD4AE] bg-[#F7FBEE] text-[#2E5B2F] hover:bg-[#ECF6DC]">{post.count??0} people looking for company <ChevronRight/></Button>:<Button onClick={()=>onSelect(post)} variant="outline" className="mt-4 w-full">View details <ChevronRight/></Button>}</article>})}</div></div>; }
