"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowLeft,ArrowRight,Check,EyeOff,LogOut,Save,UserX} from "lucide-react";
import {Button} from "@/components/ui/button";
import {SignInPanel} from "./sign-in-panel";
import {CollegeVerification} from "./college-verification";
import {campusPrograms,schoolOptions} from "./lib/campus-programs";
import {studentQuestions} from "./lib/student-questions";
import type {StudentQuestion} from "./lib/student-questions";
import {INTRODUCTION_VERSION,readinessErrors,meetingOptions,interestOptions} from "./lib/introduction";
import type {StudentProfile,Preferences} from "./lib/introduction";
import {socialHref,socialPlatforms} from "./lib/social-contacts";
import type {SocialContact} from "./lib/social-contacts";
export type {StudentProfile} from "./lib/introduction";
const card="rounded-2xl border border-[#D9E0CD] bg-white p-5 sm:p-6";
const inputClass="min-h-11 w-full rounded-xl border border-[#C8D4BE] bg-white px-3 py-2 text-base focus:ring-2 focus:ring-[#6D8D5B]";
const sections=["About you","Entertainment","Interests & plans","Your communication","Review & privacy"];
const formatMap:Record<string,string[]>={"Comfortable meeting one-on-one":["Coffee or walk"],"Prefer a group first":["Small group"],"Prefer texting before meeting":["Online first"],"Depends on the person":meetingOptions,"Still figuring it out":["Online first","Small group"]};
const timeMap:Record<string,string>={"Weekday daytime":"Weekday afternoons","Weekday evening":"Weekday evenings","Weekend daytime":"Saturday","Weekend evening":"Sunday","Online chats":"Weekday evenings"};
type Block={id:string;blockedUserId:string;displayName:string|null};
type ApiResponse={error?:string;profile?:StudentProfile;blocks?:Block[]};
export function ProfileView({profile,loading,onProfileChange,onExplore}:{profile:StudentProfile|null;loading:boolean;onProfileChange:(p:StudentProfile)=>void;onExplore?:()=>void}){
 const[draft,setDraft]=useState(profile),[source,setSource]=useState(profile),[step,setStep]=useState(profile?.profileCompleted?4:profile?.onboardingStep??0),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[blocks,setBlocks]=useState<Block[]>([]),[blockError,setBlockError]=useState("");
 const heading=useRef<HTMLHeadingElement>(null);
 if(source!==profile){setSource(profile);setDraft(profile);setStep(profile?.profileCompleted?4:profile?.onboardingStep??0);}
 useEffect(()=>{if(!profile?.collegeVerified)return;let active=true;fetch("/api/safety").then(async r=>{const d=await r.json() as ApiResponse;if(!r.ok)throw new Error(d.error);if(active)setBlocks(d.blocks??[]);}).catch(e=>{if(active)setBlockError(e.message??"Could not load blocked students.");});return()=>{active=false;};},[profile?.userId,profile?.collegeVerified]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
 useEffect(()=>heading.current?.focus(),[step]);
 if(loading)return <p role="status" className={card}>Loading your account…</p>;
 if(!draft)return <SignInPanel/>;
 function edit(changes:Partial<StudentProfile>){setDraft(v=>v?{...v,...changes}:v);setDirty(true);setMessage("");}
 function preference(changes:Partial<Preferences>){if(draft)edit({preferences:{...draft.preferences,...changes}});}
 function answer(id:string,values:string[]){if(!draft)return;const changes:Partial<StudentProfile>={preferences:{...draft.preferences,answers:{...draft.preferences.answers,[id]:values}}};
   if(id==="52")changes.meetingFormats=formatMap[values[0]]??[];
   if(id==="38")changes.availability=values.map(v=>timeMap[v]).filter(Boolean);
   if(id==="36")changes.discoveryScope=values[0]==="My school only"?"same-school":"all";
   if(id==="37"&&values.includes("No introductions now"))changes.discoveryEnabled=false;
   edit(changes);
 }
 async function save(intent:"draft"|"complete",next=step){if(!draft)return;setSaving(true);setError("");setMessage("");try{const r=await fetch("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,preferences:{...draft.preferences,answers:Object.fromEntries(Object.entries(draft.preferences.answers).map(([id,values])=>[id,[...new Set(values.map(v=>v.trim()).filter(Boolean))]]))},intent,onboardingStep:next})}),d=await r.json() as ApiResponse;if(!r.ok||!d.profile)throw new Error(d.error??"Could not save. Your answers are still here.");setDirty(false);onProfileChange(d.profile);setStep(next);setMessage(intent==="draft"?"Draft saved. Discovery is paused until you finish.":"Profile saved. Join an activity to meet willing students.");}catch(e){setError(e instanceof Error?e.message:"Please retry.");}finally{setSaving(false);}}
 async function pause(){setSaving(true);setError("");try{const r=await fetch("/api/profile",{method:"PATCH"}),d=await r.json() as ApiResponse;if(!r.ok)throw new Error(d.error);edit({discoveryEnabled:false});setMessage("Discovery paused. Pending invitations cancelled.");}catch(e){setError(e instanceof Error?e.message:"Please retry.");}finally{setSaving(false);}}
 function contact(index:number,changes:Partial<SocialContact>){if(!draft)return;edit({socialContacts:draft.socialContacts.map((c,i)=>i===index?{...c,...changes}:c)});}
 const p=draft.preferences,missing=readinessErrors(draft),shown=studentQuestions.filter(q=>q.section===step),core=shown.filter(q=>q.core),optional=draft.profileCompleted?shown.filter(q=>!q.core):[];
 return <div className="space-y-5"><section className="rounded-3xl bg-[#17392B] p-6 text-white sm:p-8"><p className="text-sm font-bold text-[#D8FF48]">Your WoxRadar introduction</p><h1 ref={heading} tabIndex={-1} className="mt-3 text-3xl font-bold outline-none">{sections[step]}</h1><p className="mt-3 text-base leading-6 text-[#C4D7C8]">Pick what feels like you. No right or wrong answers. Entertainment and social questions are optional.</p><nav aria-label="Profile sections" className="mt-5 flex flex-wrap gap-2">{sections.map((v,i)=><button key={v} type="button" onClick={()=>setStep(i)} aria-current={i===step?"step":undefined} className={"min-h-11 rounded-xl px-3 text-sm "+(i===step?"bg-[#D8FF48] font-bold text-[#17392B]":"bg-white/10")}>{i+1}. {v}</button>)}</nav></section>
 <section className={card}><p className="text-sm font-semibold">Signed in with ChatGPT</p><p className="mt-1 break-all text-base">{draft.email}</p><a href="/signout-with-chatgpt?return_to=%2Flogin" target="_top" className="mt-2 inline-flex min-h-11 items-center gap-2 text-sm underline"><LogOut className="size-4"/>Sign out</a></section>
 {draft.onboardingVersion<INTRODUCTION_VERSION?<p role="status" className="rounded-xl border border-[#D7C990] bg-[#FFFBEA] p-4 text-sm leading-6 text-[#6A5A25]">The introduction is now shorter. Review the core questions and finish again to resume discovery.</p>:null}
 {step===0&&<><CollegeVerification initialEmail={draft.email} onVerified={email=>edit({collegeVerified:true,collegeEmail:email})}/><section className={card}><h2 className="text-lg font-bold">A little campus context</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="What should people call you?"><input autoComplete="nickname" maxLength={70} value={draft.displayName} onChange={e=>edit({displayName:e.target.value})} className={inputClass}/></Field><CampusChoice label="Which school are you in?" options={schoolOptions} value={draft.school} onChange={school=>edit({school,course:""})} maxLength={80}/><CampusChoice key={draft.school} label="Which course are you doing?" options={campusPrograms[draft.school]??[]} value={draft.course} onChange={course=>edit({course})} maxLength={70} disabled={!draft.school}/><Field label="Which year of your course are you in?"><select className={inputClass} value={draft.year} onChange={e=>edit({year:e.target.value})}><option value="">Choose your year</option>{["1","2","3","4","5"].map(v=><option key={v} value={v}>Year {v}</option>)}<option value="6+">Year 6 or later</option><option value="research">Research stage</option><option value="exchange">Exchange/visiting semester</option><option value="alumni">Alumni</option></select></Field></div><p className="mt-3 text-sm text-[#607767]">Your display name, school, course and year appear on eligible match cards. These details are self-reported.</p></section>
 <section className={card}><h2 className="text-lg font-bold">One way to keep in touch</h2><p className="mt-2 text-base leading-6 text-[#607767]">Add at least one account. WoxRadar validates its platform and link format. Use the preview to confirm the account exists; ownership cannot be proven without signing in through that provider. Contacts stay private until both students choose to share.</p>{draft.socialContacts.map((c,i)=><SocialContactRow key={i} contactValue={c} onChange={changes=>contact(i,changes)} onRemove={()=>edit({socialContacts:draft.socialContacts.filter((_,j)=>j!==i)})}/>)}<Button variant="outline" className="mt-4" disabled={draft.socialContacts.length>=6} onClick={()=>edit({socialContacts:[...draft.socialContacts,{platform:"Instagram",value:""}]})}>Add social contact</Button></section></>}
 {step<4&&core.map(q=><Question key={q.id} question={q} values={p.answers[q.id]??[]} onChange={values=>answer(q.id,values)}/>)}
 {step<4&&optional.length>0&&<details className={card}><summary className="min-h-11 cursor-pointer text-base font-bold">{step===0?"Add more background":step===1?"Sharpen entertainment matches":step===2?"Add more about your plans":"Add more about communication"}</summary><p className="my-3 text-sm leading-6 text-[#607767]">These later questions are optional. Answer a few whenever you want to sharpen future suggestions.</p><div className="space-y-5">{optional.map(q=><Question key={q.id} question={q} values={p.answers[q.id]??[]} onChange={values=>answer(q.id,values)}/>)}</div></details>}
 {step===2&&<section className={card}><Field label="Where should we look for people?"><select className={inputClass} value={draft.discoveryScope} onChange={e=>edit({discoveryScope:e.target.value as StudentProfile["discoveryScope"]})}><option value="all">Across Woxsen schools and years</option><option value="same-school">My school only</option><option value="same-year">My year only</option></select></Field><p className="mt-3 text-sm text-[#607767]">Both people's restrictions apply. School preference answers never override these settings.</p><details className="mt-4"><summary className="min-h-11 cursor-pointer text-sm font-semibold">Review earlier interests</summary><div className="mt-3 flex flex-wrap gap-2">{interestOptions.map(v=><button key={v} type="button" aria-pressed={draft.interests.includes(v)} onClick={()=>edit({interests:draft.interests.includes(v)?draft.interests.filter(x=>x!==v):draft.interests.length<8?[...draft.interests,v]:draft.interests})} className={"min-h-11 rounded-full border px-3 text-sm "+(draft.interests.includes(v)?"bg-[#17392B] text-white":"bg-white")}>{v}</button>)}</div></details></section>}
 {step===4&&<><section className={card}><h2 className="text-lg font-bold">Your introduction</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><Summary label="Campus" value={[draft.displayName,draft.school,draft.course,draft.year].join(" · ")}/><Summary label="College email" value={draft.collegeVerified?"Verified":"Not verified yet"}/><Summary label="Entertainment" value={[...(p.answers["10"]??[]),...(p.answers["11"]??[]),...(p.answers["17"]??[])].join(", ")}/><Summary label="Here for" value={(p.answers["29"]??[]).join(", ")}/><Summary label="First hello" value={(p.answers["52"]??[]).join(", ")}/><Summary label="Private contacts" value={draft.socialContacts.map(c=>c.platform).join(", ")}/></dl><p className="mt-4 text-sm text-[#607767]">Use the section buttons to change your answers. Optional unanswered questions don't lower your standing.</p></section>
 <section className={card}><h2 className="text-lg font-bold">Your choices, your privacy</h2><p className="mt-2 text-base leading-6 text-[#607767]">The pilot is for adults aged 18 or older. Only enable discovery if you're eligible. Gender, background, communication answers, and contacts are never included in match cards.</p><Consent checked={draft.discoveryEnabled} onChange={v=>edit({discoveryEnabled:v})} label="Let verified students discover me in activities I join"/><Consent checked={p.shareEntertainment} onChange={v=>preference({shareEntertainment:v})} label="Use my selected entertainment and hobby topics as shared reasons on eligible match cards"/><Consent checked={p.languageMatchingOptIn} onChange={v=>preference({languageMatchingOptIn:v})} label="Use my stated chatting languages for matching and shared-language explanations"/><p className="mt-4 text-sm leading-6 text-[#607767]">College verification is required to finish. Saving profile changes cancels pending invitations. Removing a social contact removes it from future contact exchanges.</p>{missing.length>0&&<div className="mt-4 rounded-xl bg-[#FFFBEA] p-4 text-sm"><b>Before finishing</b><ul className="mt-2 list-disc space-y-1 pl-5">{missing.map(v=><li key={v}>{v}</li>)}</ul></div>}{!draft.collegeVerified&&<p className="mt-3 text-sm">Verify your college email in About you before finishing.</p>}</section></>}
 <div className="flex flex-wrap justify-between gap-3 rounded-2xl border bg-white p-4"><Button variant="outline" disabled={!step||saving} onClick={()=>setStep(v=>v-1)}><ArrowLeft/>Back</Button><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={saving} onClick={()=>save("draft")}><Save/>Save draft</Button>{step<4?<Button disabled={saving} onClick={()=>save("draft",step+1)}>Save & continue<ArrowRight/></Button>:<Button disabled={saving} onClick={()=>save("complete",4)}><Check/>{saving?"Saving…":"Finish introduction"}</Button>}</div></div><p className="text-sm text-[#607767]">{dirty?"You have unsaved changes. ":""}Skipped questions can be added later.</p>{error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{message&&<div role="status" className="rounded-xl bg-[#EAF5D0] p-4 text-sm">{message}{draft.profileCompleted&&onExplore&&<Button variant="outline" className="ml-2" onClick={onExplore}>Explore activities</Button>}</div>}
 <section className={card}><h2 className="text-lg font-bold">Discovery and blocked students</h2><Button variant="outline" className="mt-3" disabled={saving} onClick={pause}><EyeOff/>Pause discovery</Button>{blockError&&<p role="alert" className="mt-3 text-sm text-red-700">{blockError}</p>}{blocks.map(b=><div key={b.id} className="mt-3 flex items-center gap-3 rounded-xl bg-[#F5F8F0] p-3"><UserX className="size-4"/><span className="flex-1 text-sm">{b.displayName??"Blocked student"}</span><Button variant="outline" onClick={async()=>{setBlockError("");try{const r=await fetch("/api/safety",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({targetUserId:b.blockedUserId})});if(!r.ok)throw new Error("Could not unblock. Retry.");setBlocks(v=>v.filter(x=>x.id!==b.id));}catch(e){setBlockError(e instanceof Error?e.message:"Retry.");}}}>Unblock</Button></div>)}</section></div>;
}
function Consent({checked,onChange,label}:{checked:boolean;onChange:(v:boolean)=>void;label:string}){return <label className="mt-4 flex cursor-pointer items-start gap-3 rounded-xl border p-4 text-base"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="mt-1 size-5 accent-[#17392B]"/>{label}</label>;}
function Question({question:q,values,onChange}:{question:StudentQuestion;values:string[];onChange:(v:string[])=>void}){
 const exclusive=(v:string)=>/^(Depends|Anything good|Still figuring|Still exploring|No preference|Not right now|Not making|Nothing specific|A bit of everything|A mix of everything|It changes|I don't|I’m only|I'm only|Prefer not)/i.test(v);
 function toggle(v:string){if(q.max===1){onChange(values[0]===v?[]:[v]);return;}if(values.includes(v)){onChange(values.filter(x=>x!==v));return;}const next=exclusive(v)?[v]:[...values.filter(x=>!exclusive(x)),v];if(next.length<=q.max)onChange(next);}
 const customLabel="Describe in your own words";
 const customSelected=q.customText&&values[0]?.startsWith(customLabel);
 const customValue=customSelected?values[0].slice(customLabel.length).replace(/^:\s*/,""):"";
 return <fieldset className={card}><legend className="float-left w-full text-lg font-bold">{q.title}</legend><div className="clear-both pt-2"><p className="text-sm text-[#607767]">Optional · {q.text?(q.max===1?"one short answer":`up to ${q.max} answers, one per line`):q.max===1?"choose one":`choose up to ${q.max}`}</p>{q.text?<textarea aria-label={q.title} rows={3} maxLength={700} value={values.join("\n")} onChange={e=>onChange(e.target.value.split("\n").slice(0,q.max))} placeholder="Add something you'd enjoy talking about" className={inputClass+" mt-4"}/>:<div className="mt-4 flex flex-wrap gap-2">{q.options.map(v=>{const selected=q.customText&&v===customLabel?Boolean(customSelected):values.includes(v);return <button key={v} type="button" aria-pressed={selected} onClick={()=>toggle(v)} className={"min-h-11 rounded-full border px-4 py-2 text-sm "+(selected?"border-[#17392B] bg-[#17392B] text-white":"border-[#C8D4BE] bg-white text-[#48604F]")}>{selected&&<Check className="mr-1 inline size-4"/>}{v}</button>})}</div>}{customSelected?<textarea aria-label="Describe your gender in your own words" rows={2} maxLength={120} value={customValue} onChange={e=>onChange([e.target.value?`${customLabel}: ${e.target.value}`:customLabel])} placeholder="Write a description (optional)" className={inputClass+" mt-4"}/>:null}<button type="button" className="mt-3 min-h-11 text-sm underline" onClick={()=>onChange([])}>Skip / clear answer</button></div></fieldset>;
}
function SocialContactRow({contactValue,onChange,onRemove}:{contactValue:SocialContact;onChange:(changes:Partial<SocialContact>)=>void;onRemove:()=>void}){
 const href=socialHref(contactValue);
 return <div className="mt-4 rounded-xl border border-[#D9E0CD] p-3"><div className="grid gap-3 sm:grid-cols-[150px_1fr_auto]"><Field label="Platform"><select value={contactValue.platform} onChange={e=>onChange({platform:e.target.value as SocialContact["platform"]})} className={inputClass}>{socialPlatforms.map(v=><option key={v}>{v}</option>)}</select></Field><Field label={contactValue.platform==="WhatsApp"?"International number or wa.me link":contactValue.platform==="LinkedIn"||contactValue.platform==="Other"?"HTTPS profile link":"Handle or HTTPS profile link"}><input autoComplete="off" maxLength={240} value={contactValue.value} onChange={e=>onChange({value:e.target.value})} className={inputClass} placeholder={contactValue.platform==="WhatsApp"?"+91…":contactValue.platform==="LinkedIn"?"https://www.linkedin.com/in/…":"@yourhandle"}/></Field><Button variant="outline" className="self-end" onClick={onRemove}>Remove</Button></div>{href?<p className="mt-2 text-sm text-[#315E33]">Format accepted · <a href={href} target="_blank" rel="noopener noreferrer" className="font-semibold underline">Open profile to confirm</a></p>:contactValue.value?<p role="alert" className="mt-2 text-sm text-red-700">This does not match the selected platform’s profile format.</p>:null}</div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="grid gap-2 text-sm font-semibold text-[#48604F]"><span>{label}</span>{children}</label>; }
function CampusChoice({label,options,value,onChange,maxLength,disabled=false}:{label:string;options:string[];value:string;onChange:(value:string)=>void;maxLength:number;disabled?:boolean}) {
  const [otherSelected,setOtherSelected] = useState(Boolean(value && !options.includes(value)));
  const isOther = otherSelected || Boolean(value && !options.includes(value));
  return <div className="space-y-2"><Field label={label}><select disabled={disabled} value={isOther ? "__other" : value} onChange={e=>{const other=e.target.value==="__other";setOtherSelected(other);onChange(other?"":e.target.value);}} className={inputClass}><option value="">{disabled?"Choose your school first":"Choose an option"}</option>{options.map(option=><option key={option} value={option}>{option}</option>)}<option value="__other">Other / not listed</option></select></Field>{isOther && <Field label={label.includes("school")?"Other school name":"Other course or specialization"}><input value={value} onChange={e=>onChange(e.target.value)} maxLength={maxLength} placeholder="Enter the missing option" className={inputClass}/></Field>}</div>;
}
function Summary({label,value}:{label:string;value:string}) { return <div><dt className="text-sm text-[#607767]">{label}</dt><dd className="mt-1 break-words">{value || "Not answered"}</dd></div>; }
