"use client";
import{useEffect,useState}from"react";
import{Button}from"@/components/ui/button";
type Report={id:string;targetType:string;reason:string;state:string;content:string|null;createdAt:number};
type Suspended={userId:string;displayName:string|null};
type ApiResponse={error?:string;reports?:Report[];suspended?:Suspended[]};
export default function Moderation(){const[reports,setReports]=useState<Report[]>([]),[suspended,setSuspended]=useState<Suspended[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 async function load(){setError("");try{const r=await fetch("/api/moderation",{cache:"no-store"}),d=await r.json() as ApiResponse;if(!r.ok)throw new Error(d.error);setReports(d.reports??[]);setSuspended(d.suspended??[]);}catch(e){setError(e instanceof Error?e.message:"Retry.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function action(data:unknown){setBusy(true);setError("");try{const r=await fetch("/api/moderation",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}),d=await r.json() as ApiResponse;if(!r.ok)throw new Error(d.error);await load();}catch(e){setError(e instanceof Error?e.message:"Retry.");}finally{setBusy(false);}}
 return <main className="min-h-screen bg-[#F7F9F2] p-4 text-[#17392B] sm:p-8"><div className="mx-auto max-w-3xl space-y-5"><a href="/" className="inline-block min-h-11 text-base underline">Back to WoxRadar</a><h1 className="text-3xl font-bold">Pilot report review</h1><p className="text-base">Review the reported context before acting. Removed posts stop appearing in the campus feed.</p>{loading&&<p role="status">Loading reports…</p>}{error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<Button variant="outline" disabled={busy} onClick={load}>Refresh</Button>{!loading&&!error&&!reports.length&&<p className="rounded-xl bg-white p-5">No reports yet.</p>}{reports.map(r=><article key={r.id} className="rounded-2xl border bg-white p-5"><p className="text-sm font-semibold">{r.targetType} · {r.state} · {new Date(r.createdAt).toLocaleString()}</p><p className="mt-3 whitespace-pre-wrap break-words text-base">{r.content??"Reported item unavailable"}</p><p className="mt-3 text-base">Reason: {r.reason}</p>{r.state==="open"&&<div className="mt-4 flex flex-wrap gap-3"><Button variant="outline" disabled={busy} onClick={()=>action({reportId:r.id,action:"dismiss"})}>Dismiss</Button>{["post","comment","message","circle"].includes(r.targetType)&&<Button disabled={busy} onClick={()=>action({reportId:r.id,action:"remove-content"})}>Remove content</Button>}{r.targetType==="user"&&<Button disabled={busy} onClick={()=>{if(window.confirm("Pause this student's campus access and cancel their connections?"))void action({reportId:r.id,action:"suspend-student"});}}>Pause student access</Button>}</div>}</article>)}{suspended.length>0&&<section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Paused accounts</h2>{suspended.map(s=><div key={s.userId} className="mt-3 flex items-center justify-between gap-3"><span>{s.displayName??"Student"}</span><Button variant="outline" disabled={busy} onClick={()=>action({action:"restore-student",userId:s.userId})}>Restore access</Button></div>)}</section>}</div></main>;
}
